### PR TITLE
Fixed Background music

### PR DESCRIPTION
**Pull request by thegrapeanator**
changed BG music to bg03

### CODE REVIEW

**Comment by thegrapeanator** [comment]
I have no idea on how to **not** re-commit those files

**Comment by joey776** [comment]
Update your fork

**Comment by joey776** [comment]
https://webapps.stackexchange.com/questions/28998/how-do-you-update-a-github-repo-fork-in-the-web-interface

**Comment by thegrapeanator** [comment]
I can only do that by deleting my repo and reforking

**Comment by thegrapeanator** [comment]
unless i download and use the cmd-line

**Comment by joey776** [comment]
**https://webapps.stackexchange.com/questions/28998/how-do-you-update-a-github-repo-fork-in-the-web-interface**

**Comment by thegrapeanator** [comment]
If I try to change the base fork to my fork it says I can't PR to myself

**Pull request merged**
